pipeline {
    agent any
    
    environment {
        DOCKER_IMAGE = 'huziafakhan/weather-health-app'
        TAG = 'latest'
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    echo 'Building Docker image...'
                    // path
                    sh "docker build -t ${DOCKER_IMAGE}:${TAG} ./src"
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                script {
                    echo 'Pushing Docker image to Docker Hub...'
                    // Docker Hub credentials / Jenkins credentials configure 
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USER')]) {
                        sh "echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin"
                        sh "docker push ${DOCKER_IMAGE}:${TAG}"
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline successfully complete !'
        }
        failure {
            echo 'error in the pipeline.'
        }
    }
}