apiVersion: v1
kind: Service
metadata:
  name: weather-health-service
  namespace: weather-space
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
spec:
  type: NodePort
  selector:
    app: weather-health-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080